[package]
name = "gers"
version = "0.1.0"
authors = ["Griffone <thegriffones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# vulkan library in Rust
vulkano = "0.13"